# Generated by Django 5.0.1 on 2025-10-15 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projecttemplateskill",
            name="skill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="skills.skill"
            ),
        ),
        migrations.AddField(
            model_name="projecttemplateskill",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.projecttemplate",
            ),
        ),
        migrations.AddField(
            model_name="projecttemplate",
            name="recommended_skills",
            field=models.ManyToManyField(
                blank=True, through="projects.ProjectTemplateSkill", to="skills.skill"
            ),
        ),
        migrations.AddField(
            model_name="sprint",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sprints",
                to="projects.project",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="okr",
            unique_together={("project", "quarter", "year")},
        ),
        migrations.AlterUniqueTogether(
            name="projecttemplateskill",
            unique_together={("template", "skill")},
        ),
    ]
