# Generated by Django 4.2.7 on 2025-10-16 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_initial"),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="column",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="column",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="columns",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="projects.project",
            ),
        ),
    ]
