# Generated by Django 5.0.1 on 2025-10-15 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("sprint_summary", "Resumo do Sprint"),
                            ("team_performance", "Performance do Time"),
                            ("project_health", "Saúde do Projeto"),
                            ("risk_analysis", "Análise de Riscos"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("summary", models.TextField()),
                ("data", models.JSONField(default=dict)),
                ("recommendations", models.JSONField(blank=True, default=list)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Relatório do Projeto",
                "verbose_name_plural": "Relatórios dos Projetos",
                "db_table": "project_reports",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("task_summary", "Resumo de Tarefas"),
                            ("team_velocity", "Velocity do Time"),
                            ("project_progress", "Progresso do Projeto"),
                            ("upcoming_deadlines", "Prazos Próximos"),
                            ("team_workload", "Carga de Trabalho"),
                            ("recent_activity", "Atividade Recente"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("position_x", models.PositiveIntegerField(default=0)),
                ("position_y", models.PositiveIntegerField(default=0)),
                ("width", models.PositiveIntegerField(default=4)),
                ("height", models.PositiveIntegerField(default=3)),
                ("is_visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_widgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Widget do Dashboard",
                "verbose_name_plural": "Widgets do Dashboard",
                "db_table": "dashboard_widgets",
                "ordering": ["position_y", "position_x"],
            },
        ),
        migrations.CreateModel(
            name="MetricSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("velocity", "Velocity"),
                            ("burndown", "Burndown"),
                            ("lead_time", "Lead Time"),
                            ("cycle_time", "Cycle Time"),
                            ("throughput", "Throughput"),
                            ("wip", "Work in Progress"),
                        ],
                        max_length=20,
                    ),
                ),
                ("value", models.FloatField()),
                ("period", models.CharField(max_length=50)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "calculated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Snapshot de Métrica",
                "verbose_name_plural": "Snapshots de Métricas",
                "db_table": "metric_snapshots",
                "ordering": ["-calculated_at"],
            },
        ),
    ]
