# Generated by Django 5.0.1 on 2025-10-15 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("version", models.CharField(max_length=20)),
                ("config", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("accuracy_score", models.FloatField(blank=True, null=True)),
                ("last_trained_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Modelo de IA",
                "verbose_name_plural": "Modelos de IA",
                "db_table": "ai_models",
            },
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("team_allocation", "Alocação de Time"),
                            ("skill_match", "Compatibilidade de Skills"),
                            ("delay_risk", "Risco de Atraso"),
                            ("role_suggestion", "Sugestão de Papel"),
                            ("workload_balance", "Balanceamento de Carga"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "confidence",
                    models.CharField(
                        choices=[
                            ("low", "Baixa"),
                            ("medium", "Média"),
                            ("high", "Alta"),
                        ],
                        max_length=10,
                    ),
                ),
                ("score", models.FloatField(help_text="Score de 0 a 1")),
                ("data", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("is_applied", models.BooleanField(default=False)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user_feedback",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("helpful", "Útil"),
                            ("not_helpful", "Não Útil"),
                            ("incorrect", "Incorreta"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("feedback_comment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "applied_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applied_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recomendação",
                "verbose_name_plural": "Recomendações",
                "db_table": "recommendations",
                "ordering": ["-score", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="recommendat_content_eb74c2_idx",
                    ),
                    models.Index(
                        fields=["type", "is_active"], name="recommendat_type_04b94f_idx"
                    ),
                ],
            },
        ),
    ]
