# Generated by Django 4.2.7 on 2025-10-23 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0002_initial"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamCompositionDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("notes", models.TextField(blank=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("is_submitted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="composition_drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="composition_drafts",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rascunho de Composição",
                "verbose_name_plural": "Rascunhos de Composição",
                "db_table": "team_composition_drafts",
                "ordering": ["-updated_at"],
            },
        ),
    ]
