# Generated by Django 5.0.1 on 2025-10-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Sala de Chat",
                "verbose_name_plural": "Salas de Chat",
                "db_table": "chat_rooms",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Texto"),
                            ("image", "Imagem"),
                            ("file", "Arquivo"),
                            ("system", "Sistema"),
                        ],
                        default="text",
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                ("file_url", models.URLField(blank=True, null=True)),
                ("is_edited", models.BooleanField(default=False)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Mensagem",
                "verbose_name_plural": "Mensagens",
                "db_table": "chat_messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageRead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("read_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "message_reads",
            },
        ),
    ]
