# Generated by Django 4.2.7 on 2025-10-16 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0003_alter_chatroom_options_remove_chatroom_project_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_chat_rooms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
